module.exports = {
  someSidebar: {
    Spectacular: ['spectacular/index', 'spectacular/getting-started'],
    'Application Testing API': ['application-testing/index'],
    'Feature Testing API': ['feature-testing/index'],
    'Pipe Testing API': ['pipe-testing/index'],
    'API reference': [
      {
        type: 'autogenerated',
        dirName: 'api', // out directory
      },
    ],
  },
};
