// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: ['spectacular/index', 'spectacular/getting-started'],
  application: ['application-testing/index'],
  feature: [
    {
      type: 'autogenerated',
      dirName: 'feature-testing',
    },
  ],
  pipe: ['pipe-testing/index'],
  api: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'Readme',
    },
    {
      type: 'doc',
      id: 'api/globals',
      label: 'API reference',
    },
    ...require('./docs/api/typedoc-sidebar.cjs'),
  ],
};
