import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';

const sidebars: SidebarsConfig = {
  docs: ['spectacular/index', 'spectacular/getting-started'],
  application: [
    {
      type: 'autogenerated',
      dirName: 'application-testing',
    },
  ],
  feature: [
    {
      type: 'autogenerated',
      dirName: 'feature-testing',
    },
  ],
  pipe: ['pipe-testing/index'],
  api: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'Readme',
    },
    {
      type: 'doc',
      id: 'api/globals',
      label: 'API reference',
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Typedoc generates `SidebarsConfig` type annotation instead of `SidebarConfig`
    ...(typedocSidebar['items'] as any[]),
  ],
};

export default sidebars;
