module.exports = {
  someSidebar: {
    Docusaurus: ['doc1', 'doc2', 'doc3', 'mdx'],
    Spectacular: ['spectacular/getting-started'],
    'Application Testing API': [],
    'API reference': [
      {
        type: 'autogenerated',
        dirName: 'api', // out directory
      },
    ],
  },
};
