name: 'Affected'
description: 'Check whether an Nx workspace project is affected by changes.'
inputs:
  project:
    description: 'The name of the project to check.'
    required: true
outputs:
  is-affected:
    description: 'Whether or not the project is affected by changes.'
    value: ${{ steps.affected.outputs.is-affected }}

runs:
  using: 'composite'
  steps:
    - run: |
      export IS_AFFECTED=$( node ${{github.action_path}}/affected.mjs ${{ inputs.project }} )
      echo "::set-env name=IS_AFFECTED::$IS_AFFECTED"
    - id: affected
      run:
        echo "::set-output name=is-affected::$( echo $IS_AFFECTED )"
      shell: bash
