name: 'Affected'
description: 'Check whether an Nx workspace project is affected by changes.'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

inputs:
  project:
    description: 'The name of the project to check.'
    required: true
outputs:
  is-affected:
    description: 'Whether or not the project is affected by changes.'
    value: ${{ steps.affected.outputs.is-affected }}

runs:
  using: 'composite'
  steps:
    - run: mkdir tmp
      shell: bash
    - run: touch ./tmp/IS_AFFECTED
      shell: bash
    - run:
        node ${{github.action_path}}/affected.mjs ${{ inputs.project }} >>
        ./tmp/IS_AFFECTED
      shell: bash
    - run: echo "::set-output name=is-affected::$(cat ./tmp/IS_AFFECTED)"
      shell: bash
    - run: rm ./tmp/IS_AFFECTED
      shell: bash
