name: '@ngworker CI pipeline'

env:
  NODE_OPTIONS: --max_old_space_size=4096
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --non-interactive --silent
      - if: github.event_name == 'push'
        run: yarn lint
      - if: github.event_name == 'pull_request'
        run: yarn affected:lint --base=origin/main

  test:
    runs-on: ubuntu-20.04

    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --non-interactive --silent
      - if: github.event_name == 'push'
        run: yarn test
      - if: github.event_name == 'pull_request'
        run: yarn affected:test --base=origin/main

  build:
    runs-on: ubuntu-20.04

    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --non-interactive --silent
      - if: github.event_name == 'push'
        run: yarn build
      - if: github.event_name == 'pull_request'
        run: yarn affected:build --base=origin/main
      - uses: actions/upload-artifact@v2
        with:
          name: angular-package
          path: dist/packages/angular
          if-no-files-found: warn

  e2e:
    runs-on: ubuntu-20.04

    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Variable-Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --non-interactive --silent
      - run: yarn e2e --skip-nx-cache
